{
  config,
  pkgs,
  osConfig,
  ...
}:

let
  role = osConfig.portable.role;
  peerHost = osConfig.portable.peerHost;

  # Wrapper baked with the peer host. Retries a mosh tmux session to the home
  # box a few times; if home is unreachable (or no peer configured) it falls
  # back to a local shell so the floating window lands at a usable prompt
  # instead of closing.
  homeTerminal = pkgs.writeShellApplication {
    name = "home-terminal";
    runtimeInputs = [ pkgs.mosh ];
    text = ''
      PEER=${pkgs.lib.escapeShellArg peerHost}

      if [ -z "$PEER" ]; then
        exec "''${SHELL:-${pkgs.bash}/bin/bash}"
      fi

      for _ in 1 2 3; do
        # Adaptive prediction disables local echo on fast links; force it on.
        # mosh-server never times out by default and nothing else reaps it,
        # so this bounds orphans from SIGKILL-class client deaths (crash,
        # OOM, terminal window closed while offline). Deliberate exits don't
        # need it: mosh-client does a real shutdown handshake on
        # SIGHUP/SIGTERM and mosh-server exits in well under a second. 24h is
        # long enough that a suspended laptop reconnects fine.
        if mosh --server 'MOSH_SERVER_NETWORK_TMOUT=86400 mosh-server' --predict=always --predict-overwrite "$PEER" -- theme-hold dark tmux new-session -A -d -s remote -e THEME_MODE=dark ';' attach -t remote; then
          exit 0
        fi
        sleep 2
      done

      # Home unreachable/offline: fall back to a local shell.
      exec "''${SHELL:-${pkgs.bash}/bin/bash}"
    '';
  };

  # Attaches (or creates) the local 'remote' tmux session — the one mosh
  # sessions from the laptop land in — from a terminal launched right here on
  # home. Non-modal: Super+Enter keeps meaning "my local session"; this is a
  # separate, deliberate action for the rare occasion of walking over to the
  # home desk and wanting to see what the laptop session was doing.
  #
  # This is an independent dark session, regardless of the light home desktop
  # or the laptop's current desktop mode. `-e` seeds its first pane when the
  # session is created; on a later `-A` attach it is intentionally ignored,
  # leaving the existing remote session unchanged.
  attachRemote = pkgs.writeShellApplication {
    name = "attach-remote";
    runtimeInputs = [ pkgs.tmux ];
    text = ''
      exec tmux new-session -A -d -s remote -e THEME_MODE=dark ';' attach -t remote
    '';
  };

  roleConf =
    if role == "remote" then
      ''
        # Remote role: Super+Enter and boot connect to the home box; Super+Shift+Enter opens local Herdr.
        bind = $mainMod, Return, exec, btop-workspace exec foot --app-id foot-float home-terminal
        bind = $mainMod SHIFT, Return, exec, btop-workspace exec foot --app-id foot-float herdr
        exec-once = btop-workspace exec foot --app-id foot-float home-terminal
        # Remote laptop: lid close turns the screen off via DPMS without
        # suspending. logind ignores the lid; see modules/system/lid.nix.
        bindl = , switch:on:Lid Switch, exec, hyprctl dispatch dpms off
        bindl = , switch:off:Lid Switch, exec, hyprctl dispatch dpms on
      ''
    else
      ''
        # Home role: Super+Enter attaches to the 'main' tmux session, Super+Shift+Enter opens 'secondary', Super+Ctrl+Enter attaches the laptop's 'remote' session.
        bind = $mainMod, Return, exec, btop-workspace exec foot --app-id foot-float tmux new-session -A -s main
        bind = $mainMod SHIFT, Return, exec, btop-workspace exec foot --app-id foot-float tmux new-session -A -s secondary
        bind = $mainMod CTRL, Return, exec, btop-workspace exec foot --app-id foot-float attach-remote
      '';
in
{
  home.packages = [
    homeTerminal
    attachRemote
  ];

  xdg.configFile = {
    # Recursive so the colorscheme generated by programs/nvim-theme.nix can
    # live alongside the symlinked tree.
    "nvim" = {
      source = ../../dotfiles/nvim;
      recursive = true;
    };
    # Recursive so the generated role.conf can live alongside the symlinked tree.
    "hypr" = {
      source = ../../dotfiles/hypr;
      recursive = true;
    };
    "hypr/role.conf".text = roleConf;
    # Shell-sourceable twin of role.conf so plain dotfile scripts (which are
    # deployed verbatim and cannot be templated) can branch on the role.
    "hypr/role.env".text = ''
      HYPR_ROLE=${role}
    '';
    # Recursive so the flavor generated by programs/yazi-theme.nix can live
    # alongside the symlinked tree.
    "yazi" = {
      source = ../../dotfiles/yazi;
      recursive = true;
    };
    "znt".source = ../../dotfiles/znt;
  };
}
