# Yazi flavor
#
# Yazi is a truecolor consumer twice over: the flavor paints its chrome from
# hex, and the preview pane runs syntect against a TextMate theme that carries
# its own hex. Neither reaches the terminal's ANSI slots, so neither follows
# the phosphor ladder the way the ANSI-only TUIs do through programs/foot.nix.
# Both files are therefore generated from ../palettes.nix. They used to be
# hand-maintained under dotfiles/yazi/flavors/ and had drifted a full palette
# generation behind -- preview comments were rendering at 1.68:1.
#
# They install into the otherwise verbatim dotfiles/yazi tree, which
# programs/dotfiles.nix links recursively for exactly this reason.
#
# Only the dark flavor is generated; the light one is flavors/eink.yazi, a flat
# scheme with no ladder to map onto.
{ ... }:

let
  palettes = import ../palettes.nix;

  # Active phosphor profile; see ../palettes.nix.
  p = palettes.active;

  flavor = ''
    # Yazi VT220 Amber flavor -- UI chrome
    #
    # Generated by home/programs/yazi-theme.nix from home/palettes.nix.
    # Editing the installed copy has no effect past the next activation.
    #
    # The vt220-amber name is historical. Every colour below is one rung of
    # the active phosphor profile (${palettes.activeName}), and
    # dotfiles/yazi/theme.toml selects the flavor by this name, so it stays.
    #
    # This file is chrome only -- file list, tabs, markers, selection, dialogs.
    # Syntax highlighting in the preview pane comes from tmtheme.xml alongside it.

    [mgr]

    # Current working directory - foreground on background
    cwd = { fg = "#${p.foreground}", bg = "#${p.background}", bold = true }

    # Hovered file - reverse video for clear selection
    hovered = { fg = "#${p.background}", bg = "#${p.accent}", bold = true }

    # Preview hovered - reverse video, one step dimmer
    preview_hovered = { fg = "#${p.background}", bg = "#${p.secondaryText}" }

    # Search highlights - reverse video for visibility
    find_keyword = { fg = "#${p.background}", bg = "#${p.foreground}", bold = true }

    # Position indicator - accent
    find_position = { fg = "#${p.accent}" }

    # File markers, one ladder rung apart
    marker_copied = { fg = "#${p.accent}", bg = "#${p.accent}" }
    marker_cut = { fg = "#${p.secondaryText}", bg = "#${p.secondaryText}" }
    marker_marked = { fg = "#${p.foreground}", bg = "#${p.foreground}"}
    marker_selected = { fg = "#${p.foreground}", bg = "#${p.foreground}"}

    # Count indicators with subtle backgrounds
    count_copied = { fg = "#${p.foreground}", bg = "#${p.deepSurface}" }
    count_cut = { fg = "#${p.foreground}", bg = "#${p.subtleBorder}" }
    count_selected = { fg = "#${p.background}", bg = "#${p.accent}" }

    # Border using foreground
    border_style = { fg = "#${p.foreground}" }

    # Left empty: Yazi loads this flavor's tmtheme.xml for syntax highlighting.
    syntect_theme = ""

    [tabs]
    # Active tab - high contrast
    active = { fg = "#${p.foreground}", bg = "#${p.background}", bold = true }

    # Inactive tabs - lower contrast
    inactive = { fg = "#${p.mutedText}", bg = "#${p.deepSurface}" }

    # Tab separators
    sep_inner = { open = "[", close = "]" }
    sep_outer = { open = "", close = "" }

    [mode]
    # Normal mode - foreground on background
    normal_main = { fg = "#${p.foreground}", bg = "#${p.background}", bold = true }
    normal_alt = { fg = "#${p.accent}", bg = "#${p.background}" }

    # Select mode - inverted for distinction
    select_main = { fg = "#${p.background}", bg = "#${p.foreground}", bold = true }
    select_alt = { fg = "#${p.background}", bg = "#${p.accent}" }

    # Unset mode - mutedText to show inactive state
    unset_main = { fg = "#${p.mutedText}", bg = "#${p.deepSurface}" }
    unset_alt = { fg = "#${p.secondaryText}", bg = "#${p.deepSurface}" }

    [status]
    # Overall status bar
    overall = { fg = "#${p.foreground}", bg = "#${p.background}" }

    # Status separators
    sep_left = { open = "", close = "]" }
    sep_right = { open = "[", close = "" }

    # Permission indicators, one ladder rung apart
    perm_type = { fg = "#${p.foreground}", bold = true }
    perm_read = { fg = "#${p.accent}" }
    perm_write = { fg = "#${p.secondaryText}" }
    perm_exec = { fg = "#${p.foreground}", bold = true }
    perm_sep = { fg = "#${p.mutedText}" }

    # Progress indicators
    progress_label = { fg = "#${p.foreground}", bold = true }
    progress_normal = { fg = "#${p.background}", bg = "#${p.accent}" }
    progress_error = { fg = "#${p.background}", bg = "#${p.foreground}", bold = true }

    [which]
    # Key help display
    cols = 2
    mask = { bg = "#${p.deepSurface}" }
    cand = { fg = "#${p.foreground}", bold = true }
    rest = { fg = "#${p.accent}" }
    desc = { fg = "#${p.accent}" }
    separator = " → "
    separator_style = { fg = "#${p.mutedText}" }

    [confirm]
    # Confirmation dialogs
    border = { fg = "#${p.foreground}" }
    title = { fg = "#${p.foreground}", bold = true }
    content = { fg = "#${p.foreground}" }
    list = { fg = "#${p.accent}" }
    btn_yes = { fg = "#${p.foreground}", bg = "#${p.background}", bold = true }
    btn_no = { fg = "#${p.foreground}", bg = "#${p.background}" }

    [spot]
    # Search/spotlight features
    border = { fg = "#${p.mutedText}" }
    title = { fg = "#${p.foreground}", bold = true }
    tbl_col = { fg = "#${p.background}", bg = "#${p.secondaryText}" }
    tbl_cell = { fg = "#${p.background}", bg = "#${p.accent}" }

    [notify]
    # Notification styles - using bold for emphasis
    title_info = { fg = "#${p.foreground}", bold = true }
    title_warn = { fg = "#${p.foreground}", bg = "#${p.subtleBorder}", bold = true }
    title_error = { fg = "#${p.background}", bg = "#${p.foreground}", bold = true }

    [pick]
    # Picker dialogs
    border = { fg = "#${p.mutedText}" }
    active = { fg = "#${p.background}", bg = "#${p.accent}", bold = true }
    inactive = { fg = "#${p.secondaryText}" }

    [input]
    # Input fields
    border = { fg = "#${p.foreground}" }
    title = { fg = "#${p.foreground}", bold = true }
    value = { fg = "#${p.foreground}" }
    selected = { fg = "#${p.background}", bg = "#${p.accent}" }

    [cmp]
    # Completion menu
    border = { fg = "#${p.mutedText}" }
    active = { fg = "#${p.background}", bg = "#${p.accent}", bold = true }
    inactive = { fg = "#${p.secondaryText}" }
    # icon_file = "▸"
    # icon_folder = "▾"
    # icon_command = "›"

    [tasks]
    # Task manager
    border = { fg = "#${p.mutedText}" }
    title = { fg = "#${p.foreground}", bold = true }
    hovered = { fg = "#${p.background}", bg = "#${p.secondaryText}" }

    [help]
    # Help menu
    on = { fg = "#${p.foreground}", bold = true }
    run = { fg = "#${p.accent}" }
    desc = { fg = "#${p.secondaryText}" }
    hovered = { fg = "#${p.background}", bg = "#${p.accent}" }
    footer = { fg = "#${p.mutedText}", bg = "#${p.deepSurface}" }
    # icon_info = "ℹ"
    # icon_warn = "⚠"
    # icon_error = "✕"

    [filetype]
    # File type rules using ladder luminance distinctions
    rules = [
        # Directories - primary amber bold
        { url = "*/", fg = "#${p.foreground}", bold = true },

        # Executables - accent with bold
        { url = "*", is = "exec", fg = "#${p.accent}", bold = true },

        # Archives - secondaryText
        { mime = "application/zip", fg = "#${p.secondaryText}" },
        { mime = "application/x-tar", fg = "#${p.secondaryText}" },
        { mime = "application/x-gzip", fg = "#${p.secondaryText}" },
        { mime = "application/x-bzip", fg = "#${p.secondaryText}" },
        { mime = "application/x-7z-compressed", fg = "#${p.secondaryText}" },

        # Documents - accent
        { mime = "application/pdf", fg = "#${p.accent}" },
        { mime = "application/msword", fg = "#${p.accent}" },
        { mime = "application/vnd.*", fg = "#${p.accent}" },

        # Images - secondaryText
        { mime = "image/*", fg = "#${p.secondaryText}" },

        # Videos/Audio - mutedText
        { mime = "video/*", fg = "#${p.mutedText}" },
        { mime = "audio/*", fg = "#${p.mutedText}" },

        # Text files - foreground
        { mime = "text/*", fg = "#${p.foreground}" },

        # Code files - foreground
        { url = "*.py", fg = "#${p.foreground}" },
        { url = "*.js", fg = "#${p.foreground}" },
        { url = "*.rs", fg = "#${p.foreground}" },
        { url = "*.go", fg = "#${p.foreground}" },
        { url = "*.c", fg = "#${p.foreground}" },
        { url = "*.cpp", fg = "#${p.foreground}" },
        { url = "*.h", fg = "#${p.foreground}" },
        { url = "*.java", fg = "#${p.foreground}" },

        # Config files - secondaryText
        { url = "*.toml", fg = "#${p.secondaryText}" },
        { url = "*.yaml", fg = "#${p.secondaryText}" },
        { url = "*.yml", fg = "#${p.secondaryText}" },
        { url = "*.json", fg = "#${p.secondaryText}" },
        { url = "*.xml", fg = "#${p.secondaryText}" },
        { url = "*.ini", fg = "#${p.secondaryText}" },

        # Hidden files - mutedText
        { url = ".*", fg = "#${p.mutedText}" },

        # Symbolic links - accent italic
        { url = "*", is = "link", fg = "#${p.accent}", italic = true },

        # Broken links - foreground on deepSurface
        { url = "*", is = "orphan", fg = "#${p.foreground}", bg = "#${p.deepSurface}" },

        # Empty files - subtleBorder
        { mime = "inode/empty", fg = "#${p.subtleBorder}" },

        # Fallback - secondaryText
        { url = "*", fg = "#${p.secondaryText}" }
    ]

    [icon]
    # Upstream ships a large multicolor application-logo table. Shadow all of it
    # with one monochrome marker per category: `prepend_globs` is the first stage
    # Yazi consults, so the trailing "**" catch-all keeps upstream's `files` and
    # `exts` entries from ever being reached.
    #
    # No `fg` is set on purpose. An icon without an explicit color inherits the
    # color of its [filetype] rule, so markers follow the same luminance
    # hierarchy as the file names instead of forming a second, competing one.
    #
    # Directories are deliberately not matched here: patterns without a trailing
    # slash only match non-directories, so folders keep upstream's monochrome
    # folder glyph, which already inherits the bright directory color.
    # Since Yazi 26.5 upstream's icon table colors directory icons explicitly (a
    # generic blue folder via an `if = "dir"` cond, plus per-name icons for
    # Desktop, Downloads, etc. in `dirs`), so directories no longer pick up the
    # [filetype] "*/" color from an unstyled icon. Merged (prepend_*) rules that
    # match directories hit a 26.5 quirk that strips the whole row's colors, so
    # both lists are *replaced* instead; and because the no-fg inherit behavior
    # is broken for directories (icon and filename both lose their color) and
    # hex values are silently dropped on icon rules, the fg is the ANSI "blue"
    # slot, which this setup's terminal palettes map to the accent colour
    # (foot regular4) -- it also tracks the live green/amber phosphor swap.
    dirs = []
    conds = [
        { if = "dir & hovered", text = "", fg = "blue" },
        { if = "dir", text = "", fg = "blue" },
    ]

    prepend_globs = [
        { url = "*.{jpg,jpeg,png,gif,bmp,webp,avif,tiff,tif,ico,svg,heic,heif}", text = "" },
        { url = "*.{mp4,mkv,webm,mov,avi,m4v,mpg,mpeg,wmv,flv}", text = "" },
        { url = "*.{mp3,flac,wav,ogg,opus,m4a,aac,wma,mid,midi}", text = "" },
        { url = "*.{zip,tar,gz,tgz,bz2,xz,zst,7z,rar,lz4,lzma,iso,dmg,deb,rpm}", text = "" },
        { url = "*.{pdf,epub,mobi,djvu,doc,docx,odt,rtf,ppt,pptx,xls,xlsx,ods,odp}", text = "" },
        { url = "*.{toml,yaml,yml,json,jsonc,ini,cfg,conf,env,lock,plist,xml}", text = "" },
        { url = "*.{md,markdown,txt,text,log,rst,org,adoc,tex,csv,tsv}", text = "" },
        { url = "*.{sh,bash,zsh,fish,ps1,bat,cmd}", text = "" },
        { url = "*.{nix,c,h,cc,cpp,hpp,rs,go,py,pyi,js,mjs,cjs,ts,tsx,jsx,lua,vim,rb,pl,php,java,kt,swift,scala,hs,ml,ex,exs,erl,clj,r,jl,zig,sql,css,scss,html,htm}", text = "" },

        # Everything else, including files with no extension.
        { url = "**", text = "" },
    ]
  '';

  tmTheme = ''
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <!-- Generated by home/programs/yazi-theme.nix from home/palettes.nix. The
         vt220-amber name is historical; the colours are the active phosphor
         profile, currently ${palettes.activeName}. -->
    <plist version="1.0">
    <dict>
    	<key>name</key>
    	<string>VT220 Amber</string>
    	<key>author</key>
    	<string>Based on p7g</string>
    	<key>settings</key>
    	<array>
    		<!-- Global Settings -->
    		<dict>
    			<key>settings</key>
    			<dict>
    				<key>background</key>
    				<string>#${p.background}</string>
    				<key>foreground</key>
    				<string>#${p.foreground}</string>
    				<key>caret</key>
    				<string>#${p.foreground}</string>
    				<key>invisibles</key>
    				<string>#${p.subtleBorder}</string>
    				<key>lineHighlight</key>
    				<string>#${p.deepSurface}</string>
    				<key>selection</key>
    				<string>#${p.mutedText}</string>
    				<key>selectionBorder</key>
    				<string>#${p.mutedText}</string>
    				<key>findHighlight</key>
    				<string>#${p.subtleBorder}</string>
    				<key>findHighlightForeground</key>
    				<string>#${p.foreground}</string>
    			</dict>
    		</dict>

    		<!-- Comments: secondaryText + Italic. Not mutedText: at 2.47:1 against
    		     the background that is under the 3:1 floor, and comments are
    		     body-adjacent text that has to stay readable. secondaryText is
    		     3.90:1. See home/palettes.nix. -->
    		<dict>
    			<key>name</key>
    			<string>Comment</string>
    			<key>scope</key>
    			<string>comment</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.secondaryText}</string>
    				<key>fontStyle</key>
    				<string>italic</string>
    			</dict>
    		</dict>

    		<!-- Constants, Strings, Numbers: accent + Italic -->
    		<dict>
    			<key>name</key>
    			<string>Constant, String, Number</string>
    			<key>scope</key>
    			<string>constant, string, constant.numeric, constant.language, support.constant</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.accent}</string>
    				<key>fontStyle</key>
    				<string>italic</string>
    			</dict>
    		</dict>

    		<!-- Keywords, Control, Operators: foreground + Bold -->
    		<!-- Maps to Vim 'Statement' -->
    		<dict>
    			<key>name</key>
    			<string>Keyword, Storage, Operator</string>
    			<key>scope</key>
    			<string>keyword, storage.modifier, keyword.operator, keyword.control</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.foreground}</string>
    				<key>fontStyle</key>
    				<string>bold</string>
    			</dict>
    		</dict>

    		<!-- Types, Classes: accent -->
    		<!-- Maps to Vim 'Type' -->
    		<dict>
    			<key>name</key>
    			<string>Type, Class, Storage Type</string>
    			<key>scope</key>
    			<string>storage.type, support.type, entity.name.type, entity.name.class</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.accent}</string>
    			</dict>
    		</dict>

    		<!-- Functions: foreground -->
    		<!-- Maps to Vim 'Identifier' -->
    		<dict>
    			<key>name</key>
    			<string>Function, Identifier</string>
    			<key>scope</key>
    			<string>entity.name.function, variable, support.function</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.foreground}</string>
    			</dict>
    		</dict>

    		<!-- Preprocessor: secondaryText -->
    		<!-- Maps to Vim 'PreProc' -->
    		<dict>
    			<key>name</key>
    			<string>Preprocessor</string>
    			<key>scope</key>
    			<string>meta.preprocessor, keyword.control.import</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.secondaryText}</string>
    			</dict>
    		</dict>

    		<!-- HTML/XML Tags -->
    		<!-- Tag names are 'Statement' (Bold), Brackets are 'Special' (Normal) -->
    		<dict>
    			<key>name</key>
    			<string>Tag Name</string>
    			<key>scope</key>
    			<string>entity.name.tag</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.foreground}</string>
    				<key>fontStyle</key>
    				<string>bold</string>
    			</dict>
    		</dict>
    		<dict>
    			<key>name</key>
    			<string>Tag Attribute</string>
    			<key>scope</key>
    			<string>entity.other.attribute-name</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.foreground}</string>
    			</dict>
    		</dict>

    		<!-- Invalid/Error: foreground on deepSurface, Bold -->
    		<dict>
    			<key>name</key>
    			<string>Invalid</string>
    			<key>scope</key>
    			<string>invalid</string>
    			<key>settings</key>
    			<dict>
    				<key>background</key>
    				<string>#${p.deepSurface}</string>
    				<key>foreground</key>
    				<string>#${p.foreground}</string>
    				<key>fontStyle</key>
    				<string>bold</string>
    			</dict>
    		</dict>

    		<!-- TODO: reverse video on secondaryText, Bold -->
    		<dict>
    			<key>name</key>
    			<string>TODO</string>
    			<key>scope</key>
    			<string>comment.line.todo, meta.toc-list.TODO</string>
    			<key>settings</key>
    			<dict>
    				<key>background</key>
    				<string>#${p.secondaryText}</string>
    				<key>foreground</key>
    				<string>#${p.background}</string>
    				<key>fontStyle</key>
    				<string>bold</string>
    			</dict>
    		</dict>

    		<!-- Markup (Markdown) scopes. Every rule above names a code scope,
    		     so prose files matched nothing at all and previewed as one flat
    		     block of foreground. Markdown is the most-previewed file type in
    		     this repo, so it gets its own rungs: emphasis climbs above the
    		     body, syntax markers recede below it. -->

    		<!-- Headings: hot + Bold. The top rung, above the body, because a
    		     heading is the one thing a preview is skimmed for. -->
    		<dict>
    			<key>name</key>
    			<string>Markup Heading</string>
    			<key>scope</key>
    			<string>markup.heading, entity.name.section</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.hot}</string>
    				<key>fontStyle</key>
    				<string>bold</string>
    			</dict>
    		</dict>

    		<!-- Bold: bright, one rung under a heading -->
    		<dict>
    			<key>name</key>
    			<string>Markup Bold</string>
    			<key>scope</key>
    			<string>markup.bold</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.bright}</string>
    				<key>fontStyle</key>
    				<string>bold</string>
    			</dict>
    		</dict>

    		<!-- Italic: body rung, carried by the slant alone -->
    		<dict>
    			<key>name</key>
    			<string>Markup Italic</string>
    			<key>scope</key>
    			<string>markup.italic</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.foreground}</string>
    				<key>fontStyle</key>
    				<string>italic</string>
    			</dict>
    		</dict>

    		<!-- Inline code and fence info strings: accent, the same rung
    		     strings take above, since both are quoted literal text -->
    		<dict>
    			<key>name</key>
    			<string>Markup Raw</string>
    			<key>scope</key>
    			<string>markup.raw, markup.inline.raw, meta.code-fence</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.accent}</string>
    			</dict>
    		</dict>

    		<!-- Links: secondaryText + Underline. Underlined so a URL is still
    		     identifiable at a rung that reads as secondary. -->
    		<dict>
    			<key>name</key>
    			<string>Markup Link</string>
    			<key>scope</key>
    			<string>markup.underline.link, meta.link, string.other.link</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.secondaryText}</string>
    				<key>fontStyle</key>
    				<string>underline</string>
    			</dict>
    		</dict>

    		<!-- List bullets and quote bars: accent. Deliberately NOT
    		     `markup.list` -- in syntect's Markdown that scope spans the
    		     whole list item, so naming it drops every list line a rung
    		     below the surrounding paragraphs. `punctuation.definition
    		     .list_item` isolates the marker, which is what we want.
    		     (For ordered lists that is the `.` only, not the digit.) -->
    		<dict>
    			<key>name</key>
    			<string>Markup List, Quote</string>
    			<key>scope</key>
    			<string>punctuation.definition.list_item, markup.quote</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.accent}</string>
    			</dict>
    		</dict>

    		<!-- Syntax markers -- #, **, *, ` -- recede to mutedText. This is
    		     the one place mutedText's 2.47:1 is right: the markers are
    		     chrome around the text, not text, and dimming them is what
    		     leaves the heading itself standing alone on the top rung. -->
    		<dict>
    			<key>name</key>
    			<string>Markup Punctuation</string>
    			<key>scope</key>
    			<string>punctuation.definition.heading, punctuation.definition.bold, punctuation.definition.italic, punctuation.definition.raw</string>
    			<key>settings</key>
    			<dict>
    				<key>foreground</key>
    				<string>#${p.mutedText}</string>
    			</dict>
    		</dict>
    	</array>
    	<key>uuid</key>
    	<string>D8D5E82E-3D5B-46B5-B38E-8C841C21347D</string>
    	<key>colorSpaceName</key>
    	<string>sRGB</string>
    	<key>semanticClass</key>
    	<string>theme.dark.vt220-amber</string>
    </dict>
    </plist>
  '';
in
{
  xdg.configFile = {
    "yazi/flavors/vt220-amber.yazi/flavor.toml".text = flavor;
    "yazi/flavors/vt220-amber.yazi/tmtheme.xml".text = tmTheme;
  };
}
